-d /home/giacomo/gowin_proj/rv32imac_Zicsr_Zifencei/impl/gwsynthesis/rv32imac_Zicsr_Zifencei.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/giacomo/gowin_proj/rv32imac_Zicsr_Zifencei/src/phys/rv32imac_Zicsr_Zifencei.cst
-cfg /home/giacomo/gowin_proj/rv32imac_Zicsr_Zifencei/impl/pnr/device.cfg
-sdc /home/giacomo/gowin_proj/rv32imac_Zicsr_Zifencei/src/phys/rv32imac_Zicsr_Zifencei.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 25.000
